### ISSUE TITLE
Need "lazy mode" in COmanage Registry Basic Auth...

### ISSUE THREAD

**Issue by einar** [Internet2/comanage-registry-docker#1]
...and with this I mean 2 things. 

1. I wish the password file would be created automagically with defaults in it (admin:password). (With a check that the file doesnt exist if it's to be edited and mounted later). :)
2. A bootstrap(.sh) that includes everything that's in the README for the build options, using defaults that (could) work like John Doe & admin (or whatever was entered in the passwd-file) and instructions on how to use it. Even better if it also creates the db/email-config files (with working defaults for the database) and notifies the user where to (by default, according to compose) put these.

With this (hopefully) a user would just have to checkout this, run bootstrap and then go on to the database-image.

**Comment by skoranda** [comment]
The Dockerfile template and associated files for basic authentication will now create a basic auth password file and simple COmanage Registry configuration files to enable a simple recipe or bootstrap for evaluation purposes. The recipe simple-no-persistence contains the recipe details.
