### ISSUE TITLE
Please add minimum requirements

### ISSUE THREAD

**Issue by nwielenga** [Internet2/comanage-registry-docker#13]
While following the instructions to build the CoManage Shibboleth Docker container in a VM with .75gb RAM, the following error is generated in step 12/42 of the build:

> /bin/bash ../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..   -I/opt/shibboleth-sp/include -pthread -Wall -fPIC -O2 -DNDEBUG     -pthread  -Wall -O2 -DNDEBUG -MT saml1/core/impl/ProtocolsImpl.lo -MD -MP -MF $depbase.Tpo -c -o saml1/core/impl/ProtocolsImpl.lo saml1/core/impl/ProtocolsImpl.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
make[2]: *** [saml1/core/impl/AssertionsImpl.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:1143: recipe for target 'saml1/core/impl/AssertionsImpl.lo' failed
make[2]: Leaving directory '/var/www/html/src/saml'
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Makefile:562: recipe for target 'all-recursive' failed
make[1]: Leaving directory '/var/www/html/src'
Makefile:469: recipe for target 'all' failed`

If a VM with more RAM is used (I've tested 3GB), there are no errors, and the compilation proceeds as expected. Perhaps some guidance regarding system specs might be useful in the README, since the error message generated is unhelpful?

**Comment by skoranda** [comment]
Commit 8a74d835e4d152a473ec2c88005ddc573fea9e0b adds a note about the RAM usage during the source build and indicates that a vm with 4 GB is known too work.
