### ISSUE TITLE
Missing a general HowTo/step-by-step

### ISSUE THREAD

**Issue by einar** [Internet2/comanage-registry-docker#3]
Similar to this one: ("https://github.com/einar/docker-rt-swamid/blob/master/README.md"). To be able to better grasp what's what, how to do stuff, in what order and especially why. :) Does *NOT* have to include everything (the linked document doesnt) but it tries to give a step-by-step.

If it's possible to change values using environment variables in docker-compose instead of in the images that'd also be great to mention in this general HowTo.

**Comment by skoranda** [comment]
The documentation has been enhanced with more examples, including multiple "cut and paste" examples.
