### ISSUE TITLE
Hostname/ServerName missing

### ISSUE THREAD

**Issue by einar** [Internet2/comanage-registry-docker#8]
I miss a (documented) way to set hostname/servername in the "comanage-registry"; this makes all handling of certificates tricky. I guessed HOST_NAME environment would work as it was mentioned in the Dockerfile but it seems not to.

**Comment by skoranda** [comment]
The entrypoint scripts will now attempt to parse the value for ServerName from the X.509 certificate provided for HTTPS and use a value of 'unknown' if it cannot be parsed. A deployer may also set the environment variable SERVER_NAME explicitly and override any parsing from the certificate.
