### ISSUE TITLE
Crash when opening frontpage (may be due to missing ServerName)

### ISSUE THREAD

**Issue by einar** [Internet2/comanage-registry-docker#9]
Everything starts fine (except for Apache whining about ServerName) but when I load the frontpage I get a bunch of errors (frontpage still loads fine though so might be nothing or be due to missing ServerName):

comanage-registry_1           | 2017-06-08 13:22:27 Notice: Notice (8): Undefined variable: buttonClasses in [/srv/comanage-registry/app/View/Elements/menuUser.ctp, line 168]
comanage-registry_1           | Trace:
comanage-registry_1           | ErrorHandler::handleError() - CORE/Cake/Error/ErrorHandler.php, line 230
comanage-registry_1           | include - APP/View/Elements/menuUser.ctp, line 168
comanage-registry_1           | View::_evaluate() - CORE/Cake/View/View.php, line 971
comanage-registry_1           | View::_render() - CORE/Cake/View/View.php, line 933
comanage-registry_1           | View::_renderElement() - CORE/Cake/View/View.php, line 1224
comanage-registry_1           | View::element() - CORE/Cake/View/View.php, line 418
comanage-registry_1           | include - APP/View/Layouts/default.ctp, line 180
comanage-registry_1           | View::_evaluate() - CORE/Cake/View/View.php, line 971
comanage-registry_1           | View::_render() - CORE/Cake/View/View.php, line 933
comanage-registry_1           | View::renderLayout() - CORE/Cake/View/View.php, line 546
comanage-registry_1           | View::render() - CORE/Cake/View/View.php, line 481
comanage-registry_1           | Controller::render() - CORE/Cake/Controller/Controller.php, line 963
comanage-registry_1           | PagesController::display() - APP/Controller/PagesController.php, line 129
comanage-registry_1           | ReflectionMethod::invokeArgs() - [internal], line ??
comanage-registry_1           | Controller::invokeAction() - CORE/Cake/Controller/Controller.php, line 491
comanage-registry_1           | Dispatcher::_invoke() - CORE/Cake/Routing/Dispatcher.php, line 193
comanage-registry_1           | Dispatcher::dispatch() - CORE/Cake/Routing/Dispatcher.php, line 167
comanage-registry_1           | [main] - APP/webroot/index.php, line 96

**Comment by skoranda** [comment]
The output is a "Notice" and so not a fatal error or warning. Usually such notices from the CakePHP framework can be ignored.

That being said, I cannot reproduce this.

Can you make sure you are building your image with

COMANAGE_REGISTRY_VERSION=hotfix-2.0.x

and let me know if you are still able to see it?
